name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: pom.xml
      - name: Verify
        run: mvn -B --no-transfer-progress verify -Dgpg.skip=true
