name: Deploy Javadoc

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: pom.xml
      - name: Generate Javadoc
        run: mvn -B --no-transfer-progress javadoc:javadoc
      - name: Deploy Javadoc
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/target/reports/apidocs
          destination_dir: ./
